### ISSUE TITLE
Ants Table Background With Transparency

### ISSUE THREAD

**Issue by colinschoen** [colinschoen/Ants-Web-Viewer#8]
Implementation of responsive table with background color and transparency is breaking.

**Comment by jsimonian** [comment]
Set up the table to be partially transparent, stopped ant name and image highlighting and ant image dragging. Some of the ant .gifs still have opaque white backgrounds. Is this what you meant by transparency?
<img width="1162" alt="screen shot 2015-07-13 at 11 26 31 am" src="https://cloud.githubusercontent.com/assets/8609553/8657367/0cc01d0e-2952-11e5-9bc2-2206e34f8386.png">

**Comment by colinschoen** [comment]
Can you make a PR @jsimonian

**Comment by colinschoen** [comment]
This was fixed by `1.1`, closed.
